### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by martianatwork** [alfonsobries/nova-trumbowyg#10]
Getting following error on PHP 8
Type mixed cannot be marked as nullable since mixed already includes null {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type mixed cannot be marked as nullable since mixed already includes null at vendor/alfonsobries/nova-trumbowyg/src/NovaTrumbowyg.php:16)

**Comment by igorlopasovsky** [comment]
I have exactly the same problem. Have you found any solution?

**Comment by scramatte** [comment]
Same issue here but I'm running php 7.4  with Laravel 8

**Comment by alfonsobries** [comment]
I'm no longer maintaining this project
