### ISSUE TITLE
Don't use location

### ISSUE THREAD

**Issue by mvnobrega** [alfonsobries/nova-trumbowyg#5]
Hiden Content and Show Content don't use location and I can't translate.

**Comment by bvweijen** [comment]
I have the same problem so i created a pull request to fix this issue.
See: https://github.com/alfonsobries/nova-trumbowyg/pull/6

**Comment by alfonsobries** [comment]
Merged PR #6

**Comment by bvweijen** [comment]
@alfonsobries When will you release this feature? And thanks for approving!
